Repository SatelliteQE/automation-tools, pull requests merged in 2019-10, with the labels that each got.

#804 Fixes failure with upstream-nightly sat-version
  automation_tools/__init__.py
Labels: review

#806 Fix parsing MD5SUM file in order to find out ISO name
  automation_tools/__init__.py
Labels: bug

#808 Update accepted Sat GA versions
  automation_tools/__init__.py
  automation_tools/repository.py
Labels: urgent
